version: '3.8'

services:
  sniper_app:
    container_name: sniper_app
    build: .
    ports:
      - "${APP_PORT}:8501"
    volumes:
      - .:/app
    environment:
      - EXCEL_FILE=${EXCEL_FILE}
    restart: always
